---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec
  format: doc
  sudo: true
  sudo_command: . /etc/profile;

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[MUSiCC::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
